services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: queryguard
      POSTGRES_PASSWORD: queryguard
      POSTGRES_DB: queryguard
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
